/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alquilar` | `/alquilar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/buscar` | `/buscar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/comprar` | `/comprar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/proyectos` | `/proyectos`; params?: Router.UnknownInputParams; } | { pathname: `/inmobiliaria/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/listing/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/alquilar` | `/alquilar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/buscar` | `/buscar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/comprar` | `/comprar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/proyectos` | `/proyectos`; params?: Router.UnknownOutputParams; } | { pathname: `/inmobiliaria/[slug]`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `/listing/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/alquilar${`?${string}` | `#${string}` | ''}` | `/alquilar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/buscar${`?${string}` | `#${string}` | ''}` | `/buscar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/comprar${`?${string}` | `#${string}` | ''}` | `/comprar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/proyectos${`?${string}` | `#${string}` | ''}` | `/proyectos${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alquilar` | `/alquilar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/buscar` | `/buscar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/comprar` | `/comprar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/proyectos` | `/proyectos`; params?: Router.UnknownInputParams; } | `/inmobiliaria/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/listing/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/inmobiliaria/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/listing/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
